name: deploy

on:
  workflow_call:
    secrets:
      SSH_HOST:
        description: 'secret 1'
      SSH_KEY:
        description: 'secret 2'
    inputs:
      env:
        description: 'Env'
        type: string
        required: false
        default: 'dev'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
             mkdir -p /home/runner/.ssh
             echo "$SSH_KEY" > /home/runner/.ssh/github_actions
             chmod 600 /home/runner/.ssh/github_actions
             ssh-agent -a $SSH_AUTH_SOCK > /dev/null
             ssh-add /home/runner/.ssh/github_actions

      - name: Deploy env:${{ inputs.env }} ${{ github.repository }} tag ${{ github.run_number }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
             echo ${{ secrets.SSH_HOST }}
             cd .build
             export ENV=${{ inputs.env }}
             export TAG=${{ github.run_number }}
             export DOCKER_HOST=ssh://${{ secrets.ssh_host }}
             make deploy

