name: deploy

on:
  workflow_call:
    secrets:
      SSH_HOST:
        description: 'secret 1'
      SSH_KEY:
        description: 'secret 2'
      SSH_USER:
        description: 'secret 2'
    inputs:
      env:
        description: 'Env'
        type: string
        required: false
        default: 'dev'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: steel0237-sprintf/template
          path: ./tools
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy env:${{ inputs.env }} ${{ github.repository }} tag ${{ github.run_number }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
             env
             export ENV=${{ inputs.env }}
             export TAG=${{ github.run_number }}
             export DOCKER_HOST=ssh://${{ inputs.ssh_host }}
             pwd
             ls -la 
             cd /home/runner/work/test/test/tools
             ls -la
