name: php build

on:
  workflow_call:
    inputs:
      php_version:
        description: 'Version of PHP to run builds on'
        type: string
        required: false
        default: '7.4'
      env:
        description: 'Env'
        type: string
        required: false
        default: 'dev'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image for ${{ github.repository }} tag ${{ github.run_number }} and push GHCR
        run: |
             export ENV=${{ inputs.env }}
             export TAG=${{ github.run_number }}
             find app_putevka/config -name '*.'${ENV} -exec sh -c 'mv "$0" "${0%.${ENV}}.php"' {} \;
             ls -la app_putevka/config
             cd .build
             make push
