name: php build

on:
  workflow_call:
    inputs:
      php_version:
        description: 'Version of PHP to run builds on'
        type: string
        required: false
        default: '7.4'
      env:
        description: 'Env'
        type: string
        required: false
        default: 'dev'
      config:
        description: 'config'
        type: string
        required: false
        default: 'dev'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    steps:
      - name: Build the Docker image for ${{ github.repository }} tag ${{ github.run_number }} and push GHCR
        run: |
             export ENV=${{ inputs.env }}
             export CONFIG=${{ inputs.config }}
             export TAG=${{ github.run_number }}
             echo $CONFIG
             echo $ENV
             env
             echo ${{ vars.CONFIG_JSON }}

            # find app_putevka/config -name '*.'${ENV} -exec sh -c 'mv "$0" "${0%.${ENV}}.php"' {} \;
            # ls -la app_putevka/config
            # cd .build
            # make push
